# Dockerfile for Logstash
FROM docker.elastic.co/logstash/logstash:7.17.0

# Copy Logstash configuration
COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf

CMD ["logstash", "-f", "/usr/share/logstash/pipeline/logstash.conf"]

